import {
  Archive,
  Award,
  Baby,
  BarChart3,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  ClipboardList,
  Clock,
  Crown,
  FileText,
  Flame,
  Folder,
  Gem,
  Handshake,
  Heart,
  HeartHandshake,
  Inbox,
  Landmark,
  Medal,
  Megaphone,
  PieChart,
  Presentation,
  Rocket,
  Smile,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  User,
  UserPlus,
  Users,
  Zap,
} from '@lucide/vue';

import type { WorkspaceIconCategory } from '@/lib/workspaces';

export const workIconCategories: WorkspaceIconCategory[] = [
  {
    label: 'Work',
    icons: {
      briefcase: Briefcase,
      building: Building,
      'building-2': Building2,
      landmark: Landmark,
      presentation: Presentation,
      calculator: Calculator,
      'clipboard-list': ClipboardList,
      'file-text': FileText,
      folder: Folder,
      archive: Archive,
      inbox: Inbox,
      calendar: Calendar,
      clock: Clock,
    },
  },
  {
    label: 'Growth',
    icons: {
      rocket: Rocket,
      megaphone: Megaphone,
      target: Target,
      'trending-up': TrendingUp,
      'bar-chart': BarChart3,
      'pie-chart': PieChart,
      sparkles: Sparkles,
      flame: Flame,
      zap: Zap,
      star: Star,
      gem: Gem,
      trophy: Trophy,
      award: Award,
      medal: Medal,
      crown: Crown,
    },
  },
  {
    label: 'People',
    icons: {
      users: Users,
      user: User,
      'user-plus': UserPlus,
      handshake: Handshake,
      'heart-handshake': HeartHandshake,
      heart: Heart,
      smile: Smile,
      baby: Baby,
    },
  },
];
