import {
  Anchor,
  Apple,
  Atom,
  Beer,
  Bell,
  Bike,
  Book,
  BookOpen,
  Bookmark,
  Brush,
  Cake,
  Camera,
  Car,
  Clapperboard,
  Coffee,
  Compass,
  Cookie,
  Dumbbell,
  Film,
  Flag,
  GraduationCap,
  Headphones,
  Home,
  IceCream,
  Key,
  Lightbulb,
  Lock,
  Luggage,
  Map,
  MapPin,
  Mic,
  Music,
  Palette,
  Pencil,
  PenTool,
  Pizza,
  Plane,
  Puzzle,
  Shield,
  Ship,
  Tent,
  Utensils,
  Wine,
} from '@lucide/vue';

import type { WorkspaceIconCategory } from '@/lib/workspaces';

export const leisureIconCategories: WorkspaceIconCategory[] = [
  {
    label: 'Food & travel',
    icons: {
      coffee: Coffee,
      pizza: Pizza,
      utensils: Utensils,
      cake: Cake,
      apple: Apple,
      beer: Beer,
      wine: Wine,
      'ice-cream': IceCream,
      cookie: Cookie,
      plane: Plane,
      car: Car,
      bike: Bike,
      ship: Ship,
      map: Map,
      'map-pin': MapPin,
      compass: Compass,
      tent: Tent,
      luggage: Luggage,
    },
  },
  {
    label: 'Creative & more',
    icons: {
      'graduation-cap': GraduationCap,
      book: Book,
      'book-open': BookOpen,
      pencil: Pencil,
      'pen-tool': PenTool,
      palette: Palette,
      brush: Brush,
      music: Music,
      mic: Mic,
      camera: Camera,
      film: Film,
      clapperboard: Clapperboard,
      headphones: Headphones,
      puzzle: Puzzle,
      lightbulb: Lightbulb,
      key: Key,
      lock: Lock,
      shield: Shield,
      bell: Bell,
      bookmark: Bookmark,
      flag: Flag,
      anchor: Anchor,
      atom: Atom,
      dumbbell: Dumbbell,
      home: Home,
    },
  },
];
