import {
    Anchor,
    Apple,
    Archive,
    Atom,
    Award,
    Baby,
    Banknote,
    BarChart3,
    Beer,
    Bell,
    Bike,
    Bird,
    Book,
    BookOpen,
    Bookmark,
    Bot,
    Briefcase,
    Brush,
    Bug,
    Building,
    Building2,
    Cake,
    Calculator,
    Calendar,
    Camera,
    Car,
    Cat,
    Clapperboard,
    ClipboardList,
    Clock,
    Cloud,
    Code,
    Coffee,
    Coins,
    Compass,
    Cookie,
    Cpu,
    CreditCard,
    Crown,
    Database,
    Dog,
    Dumbbell,
    FileText,
    Film,
    Fish,
    Flag,
    Flame,
    Flower2,
    Folder,
    Gamepad2,
    Gem,
    Gift,
    Globe2,
    GraduationCap,
    Hammer,
    Handshake,
    Headphones,
    Heart,
    HeartHandshake,
    Home,
    IceCream,
    Inbox,
    Key,
    Landmark,
    Laptop,
    Leaf,
    Lightbulb,
    Lock,
    Luggage,
    Map,
    MapPin,
    Medal,
    Megaphone,
    Mic,
    Monitor,
    Moon,
    Mountain,
    Music,
    Package,
    Palette,
    PawPrint,
    Pencil,
    PenTool,
    PieChart,
    PiggyBank,
    Pizza,
    Plane,
    Presentation,
    Puzzle,
    Rainbow,
    Rocket,
    Server,
    Settings,
    Shield,
    Ship,
    ShoppingBag,
    ShoppingCart,
    Smartphone,
    Smile,
    Snowflake,
    Sparkles,
    Sprout,
    Star,
    Store,
    Sun,
    Tag,
    Target,
    Tent,
    Terminal,
    Ticket,
    TreePine,
    TrendingUp,
    Trophy,
    Umbrella,
    User,
    UserPlus,
    Users,
    Utensils,
    Wallet,
    Waves,
    Wifi,
    Wine,
    Wrench,
    Zap,
} from '@lucide/vue';
import type { Component } from 'vue';

export type WorkspaceAppearance = {
    name: string;
    icon?: string | null;
    color?: string | null;
};

/**
 * Icon keys grouped for the picker. The flat key set mirrors
 * Workspace::ICONS on the backend — keep both in sync.
 */
export const WORKSPACE_ICON_CATEGORIES: { label: string; icons: Record<string, Component> }[] = [
    {
        label: 'Work',
        icons: {
            briefcase: Briefcase,
            building: Building,
            'building-2': Building2,
            landmark: Landmark,
            presentation: Presentation,
            calculator: Calculator,
            'clipboard-list': ClipboardList,
            'file-text': FileText,
            folder: Folder,
            archive: Archive,
            inbox: Inbox,
            calendar: Calendar,
            clock: Clock,
        },
    },
    {
        label: 'Growth',
        icons: {
            rocket: Rocket,
            megaphone: Megaphone,
            target: Target,
            'trending-up': TrendingUp,
            'bar-chart': BarChart3,
            'pie-chart': PieChart,
            sparkles: Sparkles,
            flame: Flame,
            zap: Zap,
            star: Star,
            gem: Gem,
            trophy: Trophy,
            award: Award,
            medal: Medal,
            crown: Crown,
        },
    },
    {
        label: 'People',
        icons: {
            users: Users,
            user: User,
            'user-plus': UserPlus,
            handshake: Handshake,
            'heart-handshake': HeartHandshake,
            heart: Heart,
            smile: Smile,
            baby: Baby,
        },
    },
    {
        label: 'Commerce',
        icons: {
            store: Store,
            'shopping-bag': ShoppingBag,
            'shopping-cart': ShoppingCart,
            package: Package,
            gift: Gift,
            'credit-card': CreditCard,
            wallet: Wallet,
            banknote: Banknote,
            coins: Coins,
            'piggy-bank': PiggyBank,
            tag: Tag,
            ticket: Ticket,
        },
    },
    {
        label: 'Tech',
        icons: {
            code: Code,
            terminal: Terminal,
            cpu: Cpu,
            database: Database,
            server: Server,
            cloud: Cloud,
            wifi: Wifi,
            globe: Globe2,
            monitor: Monitor,
            smartphone: Smartphone,
            laptop: Laptop,
            bot: Bot,
            'gamepad-2': Gamepad2,
            wrench: Wrench,
            hammer: Hammer,
            settings: Settings,
        },
    },
    {
        label: 'Nature',
        icons: {
            leaf: Leaf,
            sprout: Sprout,
            'flower-2': Flower2,
            'tree-pine': TreePine,
            sun: Sun,
            moon: Moon,
            mountain: Mountain,
            waves: Waves,
            snowflake: Snowflake,
            umbrella: Umbrella,
            rainbow: Rainbow,
            bird: Bird,
            cat: Cat,
            dog: Dog,
            fish: Fish,
            bug: Bug,
            'paw-print': PawPrint,
        },
    },
    {
        label: 'Food & travel',
        icons: {
            coffee: Coffee,
            pizza: Pizza,
            utensils: Utensils,
            cake: Cake,
            apple: Apple,
            beer: Beer,
            wine: Wine,
            'ice-cream': IceCream,
            cookie: Cookie,
            plane: Plane,
            car: Car,
            bike: Bike,
            ship: Ship,
            map: Map,
            'map-pin': MapPin,
            compass: Compass,
            tent: Tent,
            luggage: Luggage,
        },
    },
    {
        label: 'Creative & more',
        icons: {
            'graduation-cap': GraduationCap,
            book: Book,
            'book-open': BookOpen,
            pencil: Pencil,
            'pen-tool': PenTool,
            palette: Palette,
            brush: Brush,
            music: Music,
            mic: Mic,
            camera: Camera,
            film: Film,
            clapperboard: Clapperboard,
            headphones: Headphones,
            puzzle: Puzzle,
            lightbulb: Lightbulb,
            key: Key,
            lock: Lock,
            shield: Shield,
            bell: Bell,
            bookmark: Bookmark,
            flag: Flag,
            anchor: Anchor,
            atom: Atom,
            dumbbell: Dumbbell,
            home: Home,
        },
    },
];

/** Flat lookup of every picker icon by key. */
export const WORKSPACE_ICONS: Record<string, Component> = Object.assign({}, ...WORKSPACE_ICON_CATEGORIES.map((category) => category.icons));

/** Keys mirror Workspace::COLORS on the backend. */
export const WORKSPACE_COLORS: Record<string, string> = {
    slate: '#64748b',
    red: '#ef4444',
    orange: '#f97316',
    amber: '#f59e0b',
    green: '#22c55e',
    teal: '#14b8a6',
    blue: '#3b82f6',
    violet: '#8b5cf6',
    pink: '#ec4899',
};

export function workspaceIconComponent(key?: string | null): Component | null {
    return key ? (WORKSPACE_ICONS[key] ?? null) : null;
}

export function workspaceColorHex(key?: string | null): string | null {
    return key ? (WORKSPACE_COLORS[key] ?? null) : null;
}

export function workspaceInitial(name?: string | null): string {
    return String(name ?? 'O')
        .slice(0, 1)
        .toUpperCase();
}
