import {
  Banknote,
  Bird,
  Bot,
  Bug,
  Cat,
  Cloud,
  Code,
  Coins,
  Cpu,
  CreditCard,
  Database,
  Dog,
  Fish,
  Flower2,
  Gamepad2,
  Gift,
  Globe2,
  Hammer,
  Laptop,
  Leaf,
  Monitor,
  Moon,
  Mountain,
  Package,
  PawPrint,
  PiggyBank,
  Rainbow,
  Server,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sprout,
  Store,
  Sun,
  Tag,
  Terminal,
  Ticket,
  TreePine,
  Umbrella,
  Wallet,
  Waves,
  Wifi,
  Wrench,
} from '@lucide/vue';

import type { WorkspaceIconCategory } from '@/lib/workspaces';

export const worldIconCategories: WorkspaceIconCategory[] = [
  {
    label: 'Commerce',
    icons: {
      store: Store,
      'shopping-bag': ShoppingBag,
      'shopping-cart': ShoppingCart,
      package: Package,
      gift: Gift,
      'credit-card': CreditCard,
      wallet: Wallet,
      banknote: Banknote,
      coins: Coins,
      'piggy-bank': PiggyBank,
      tag: Tag,
      ticket: Ticket,
    },
  },
  {
    label: 'Tech',
    icons: {
      code: Code,
      terminal: Terminal,
      cpu: Cpu,
      database: Database,
      server: Server,
      cloud: Cloud,
      wifi: Wifi,
      globe: Globe2,
      monitor: Monitor,
      smartphone: Smartphone,
      laptop: Laptop,
      bot: Bot,
      'gamepad-2': Gamepad2,
      wrench: Wrench,
      hammer: Hammer,
      settings: Settings,
    },
  },
  {
    label: 'Nature',
    icons: {
      leaf: Leaf,
      sprout: Sprout,
      'flower-2': Flower2,
      'tree-pine': TreePine,
      sun: Sun,
      moon: Moon,
      mountain: Mountain,
      waves: Waves,
      snowflake: Snowflake,
      umbrella: Umbrella,
      rainbow: Rainbow,
      bird: Bird,
      cat: Cat,
      dog: Dog,
      fish: Fish,
      bug: Bug,
      'paw-print': PawPrint,
    },
  },
];
